version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run: composer install
      - run: ./vendor/bin/phpunit tests
      - store_test_results