name: CI

on:
  push:
    branches: [develop, master]

  pull_request:
    branches: [develop, master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v1

      - name: Validate composer.json and composer.lock
        if: github.event_name == 'pull_request'
        run: composer validate