name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: checkout
    
    - run: sudo apt update
      
    - name: Install dependencies
    - run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
    - run: ./vendor/bin/phpunit tests
